#!/usr/bin/env node
/**
 * WEB SERVER for Vibe & Verify (display mode)
 * Reads results from report.json generated by `node run.js` in the terminal.
 * No external API calls — the app only displays pre-generated analysis.
 */
const http = require("http");
const fs   = require("fs");
const path = require("path");

const PORT = 3000;
const PUBLIC_DIR = path.join(__dirname, "public");

const MIME = {
  ".html": "text/html; charset=utf-8",
  ".css":  "text/css; charset=utf-8",
  ".js":   "application/javascript; charset=utf-8",
  ".png":  "image/png",
  ".json": "application/json",
  ".pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
};

const server = http.createServer(async (req, res) => {
  const cleanUrl = req.url.split("?")[0];
  console.log(`${new Date().toISOString()} ${req.method} ${req.url} Host=${req.headers.host || "none"}`);

  // GET /api/report — return cached report.json + latest PPTX filename
  if (req.method === "GET" && cleanUrl === "/api/report") {
    const reportPath = path.join(__dirname, "report.json");
    if (!fs.existsSync(reportPath)) {
      res.writeHead(404, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ error: "No report found" }));
      return;
    }
    try {
      const report = JSON.parse(fs.readFileSync(reportPath, "utf8"));
      const pptxFiles = fs.readdirSync(__dirname).filter(f => f.endsWith(".pptx"));
      const pptx = pptxFiles.length ? pptxFiles.sort().pop() : null;
      res.writeHead(200, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ report, pptx }));
    } catch (err) {
      res.writeHead(500, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ error: err.message }));
    }
    return;
  }

  // GET /api/download/:filename — download generated PPTX
  if (req.method === "GET" && cleanUrl.startsWith("/api/download/")) {
    const filename = decodeURIComponent(cleanUrl.slice("/api/download/".length));
    const filePath = path.join(__dirname, filename);
    if (!filePath.startsWith(__dirname) || !fs.existsSync(filePath)) {
      res.writeHead(404, { "Content-Type": "text/plain" });
      res.end("Not found");
      return;
    }
    const data = fs.readFileSync(filePath);
    res.writeHead(200, {
      "Content-Type":        MIME[".pptx"],
      "Content-Disposition": `attachment; filename="${filename}"`,
    });
    res.end(data);
    return;
  }

  // Static files
  let url = cleanUrl === "/" ? "/index.html" : cleanUrl;
  let filePath;
  if (url.startsWith("/assets/")) {
    filePath = path.join(__dirname, url);
  } else {
    filePath = path.join(PUBLIC_DIR, url);
  }

  if (!fs.existsSync(filePath)) {
    res.writeHead(404, { "Content-Type": "text/plain" });
    res.end("Not found");
    return;
  }

  const ext = path.extname(filePath);
  const contentType = MIME[ext] || "application/octet-stream";

  if (req.method === "HEAD") {
    res.writeHead(200, { "Content-Type": contentType });
    res.end();
    return;
  }

  const data = fs.readFileSync(filePath);
  res.writeHead(200, { "Content-Type": contentType });
  res.end(data);
});

server.listen(PORT, "0.0.0.0", () => {
  console.log(`Vibe & Verify server running on http://0.0.0.0:${PORT}`);
});
